update Dockerfiles for traffic-ops and traffic-vault and fix todb_bootstrap.sh to work on non local dbs

diff --git a/traffic_ops/install/bin/postinstall b/traffic_ops/install/bin/postinstall
--- a/traffic_ops/install/bin/postinstall
+++ b/traffic_ops/install/bin/postinstall
@@ -33,10 +33,10 @@ fi
 # make sure installed with proper permissions
 umask 022
 
-if [[ ! $(su - postgres psql -w -c 'show is_superuser' </dev/null 2>/dev/null) =~ 'on' ]]; then
-	echo >&2 "postinstall requires the postgres user to have superuser access to postgresql. Aborting."
-	exit 1
-fi
+#if [[ ! $(psql -U postgres -w -c 'show is_superuser' </dev/null 2>/dev/null) =~ 'on' ]]; then
+#	echo >&2 "postinstall requires the postgres user to have superuser access to postgresql. Aborting."
+#	exit 1
+#fi
 
 # install carton first
 cpanm Carton
